AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Lambda to report Service Catalog costs to the AWS Marketplace

Metadata:
  AWS::ServerlessRepo::Application:
    Name: "lambda-sc-cost-meter"
    Description: "Lambda to report Service Catalog costs to the AWS Marketplace"
    Author: "Sage-Bionetworks"
    SpdxLicenseId: "Apache-2.0"
    # paths are relative to .aws-sam/build directory
    LicenseUrl: "LICENSE"
    ReadmeUrl: "README.md"
    Labels: ["serverless", "cost", "marketplace", "billing", "metering", "reporting"]
    HomePageUrl: "https://github.com/Sage-Bionetworks-IT/lambda-template"
    SemanticVersion: "0.0.1"
    SourceCodeUrl: "https://github.com/Sage-Bionetworks-IT/lambda-template/tree/0.0.1"

Globals:
  Function:
    Timeout: 30

Resources:
  MeterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: sc_cost_meter/app.lambda_handler
      Runtime: python3.7
      Role: !GetAtt FunctionRole.Arn
      Events:
        MeterApi:
          Type: Api
          Properties:
            Path: /meter
            Method: get

  FunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MeterFunctionApi:
    Description: "API Gateway endpoint URL for Prod stage for meter function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/meter/"
  MeterFunctionArn:
    Description: "Meter Lambda Function ARN"
    Value: !GetAtt MeterFunction.Arn
  MeterFunctionRoleArn:
    Description: "Implicit IAM Role created for meter function"
    Value: !GetAtt FunctionRole.Arn
